apiVersion: v1
kind: Secret
metadata:
  name: {{include "gateway-microservice.docker-secret.name" .}}
  namespace: {{.Values.namespace}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.data | quote }}
