{{ if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "gateway-microservice.fullname" . }}
spec:

  port:
    targetPort: {{ .Values.service.httpPort}}
  to:
    kind: Service
    name: {{ include "gateway-microservice.fullname" . }}
{{ end }}