apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-microservice.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{if .Values.secret.values }}
  {{- range .Values.secret.values }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
    {{- end }}