apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice-role
  namespace: {{.Values.namespace}}  # Use the appropriate namespace*
  labels:
      {{- include "categories-microservice.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
