apiVersion: v1
kind: Secret
metadata:
  name: {{ include "categories-microservice.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range .Values.secret.values }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}