  {{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "spring-microservice.fullname" . }}
  namespace: your-namespace
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "spring-microservice.fullname" . }}
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- end }}