name: Package Helm Chart

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.8.0'  # Specify the version of Helm you want to use

      - name: Package Helm chart
        run: |
          helm package helm-charts/spring-microservice
          ls -lh

      - name: Upload Helm chart as artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: '*.tgz'
      - name: Add Helm repository
        run: helm repo add my-repo https://my-helm-repo.com/charts

      - name: Push Helm chart to repository
        run: |
          helm push helm-charts/spring-microservice-0.1.0.tgz my-repo
        env:
          HELM_PUSH_USERNAME: ${{ secrets.HELM_REPO_USERNAME }}
          HELM_PUSH_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}